version: '3'
services:
  client:
    image: node:18
    container_name: quiz_app_client
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
    depends_on:
      - server

  server:
    image: node:18
    container_name: quiz_app_api
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev"
